[program:pretixtask]
command=/usr/local/bin/pretix-task.sh
autostart=true
autorestart=true
priority=5
user=pretixuser
environment=HOME=/pretix
stopasgroup=true
stopwaitsecs=30
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:pretixcron]
command=/usr/local/bin/pretix-cron.sh
autostart=true
autorestart=true
priority=5
user=pretixuser
environment=HOME=/pretix
stopasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
